#!/bin/bash

echo Cleaning Directory
rm *.class
echo Compiling Directory
javac PeerProcessRemote.java
echo Zipping Project
tar -zcvf project.tgz .
echo Copying Project Over
osascript -e 'tell application "Terminal" to do script "cd /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; scp project.tgz nbmiller@lin309-02.cise.ufl.edu:~/Documents/"'

sleep 6s
osascript -e 'tell application "Terminal" to do script "cd /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; scp project.tgz nbmiller@lin309-03.cise.ufl.edu:~/Documents/"'

sleep 6s
osascript -e 'tell application "Terminal" to do script "cd /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; scp project.tgz nbmiller@lin309-04.cise.ufl.edu:~/Documents/"'

sleep 6s
osascript -e 'tell application "Terminal" to do script "cd /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; scp project.tgz nbmiller@lin309-05.cise.ufl.edu:~/Documents/"'

sleep 6s
osascript -e 'tell application "Terminal" to do script "cd /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; scp project.tgz nbmiller@lin309-06.cise.ufl.edu:~/Documents/"'

sleep 6s
osascript -e 'tell application "Terminal" to do script "cd /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; scp project.tgz nbmiller@lin309-07.cise.ufl.edu:~/Documents/"'

sleep 6s
