#!/bin/bash

echo Running Remote Peers

osascript -e 'tell application "Terminal" to do script "cd /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; chmod 700 ScriptPeer0; ./ScriptPeer0"'
sleep 10s
osascript -e 'tell application "Terminal" to do script "cd /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; chmod 700 ScriptPeer1; ./ScriptPeer1"'
sleep 10s
osascript -e 'tell application "Terminal" to do script "cd /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; chmod 700 ScriptPeer2; ./ScriptPeer2"'
sleep 10s
osascript -e 'tell application "Terminal" to do script "cd /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; chmod 700 ScriptPeer3; ./ScriptPeer3"'
sleep 10s
osascript -e 'tell application "Terminal" to do script "cd /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; chmod 700 ScriptPeer4; ./ScriptPeer4"'
sleep 10s
osascript -e 'tell application "Terminal" to do script "cd /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; chmod 700 ScriptPeer5; ./ScriptPeer5"'
sleep 10s
