#!/bin/bash

echo Bringing Them Boys Home

osascript -e 'tell application "Terminal" to do script "cd /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; scp nbmiller@lin309-02.cise.ufl.edu:~/Documents/logging/log_peer_1001.log /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; scp nbmiller@lin309-02.cise.ufl.edu:~/Documents/peer_1001/1001Video.mov /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2/peer_1001/"'

sleep 12s
osascript -e 'tell application "Terminal" to do script "cd /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; scp nbmiller@lin309-03.cise.ufl.edu:~/Documents/logging/log_peer_1002.log /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; scp nbmiller@lin309-03.cise.ufl.edu:~/Documents/peer_1002/1002Video.mov /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2/peer_1002/"'

sleep 12s
osascript -e 'tell application "Terminal" to do script "cd /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; scp nbmiller@lin309-04.cise.ufl.edu:~/Documents/logging/log_peer_1003.log /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; scp nbmiller@lin309-04.cise.ufl.edu:~/Documents/peer_1003/1003Video.mov /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2/peer_1003/"'

sleep 12s
osascript -e 'tell application "Terminal" to do script "cd /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; scp nbmiller@lin309-05.cise.ufl.edu:~/Documents/logging/log_peer_1004.log /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; scp nbmiller@lin309-05.cise.ufl.edu:~/Documents/peer_1004/1004Video.mov /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2/peer_1004/"'

sleep 12s
osascript -e 'tell application "Terminal" to do script "cd /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; scp nbmiller@lin309-06.cise.ufl.edu:~/Documents/logging/log_peer_1005.log /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; scp nbmiller@lin309-06.cise.ufl.edu:~/Documents/peer_1005/1005Video.mov /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2/peer_1005/"'

sleep 12s
osascript -e 'tell application "Terminal" to do script "cd /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; scp nbmiller@lin309-07.cise.ufl.edu:~/Documents/logging/log_peer_1006.log /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2; scp nbmiller@lin309-07.cise.ufl.edu:~/Documents/peer_1006/1006Video.mov /Users/nicholasmiller/Documents/Git/Class/AlmightyJitTorrent/CommandLineJitTorrent2/peer_1006/"'

sleep 12s
